plugins {
    id 'com.android.application'
}

android {
    compileSdk 36

    defaultConfig {
        applicationId "com.accessibilitymanager"
        minSdk 26
        targetSdk 35
        versionCode 103
        versionName "10.3"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file(System.getenv("SIGNING_STORE_FILE") ?: "empty.jks")
            storePassword System.getenv("SIGNING_STORE_PASSWORD")
            keyAlias System.getenv("SIGNING_KEY_ALIAS")
            keyPassword System.getenv("SIGNING_KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    namespace 'com.accessibilitymanager'
}

dependencies {
    implementation "dev.rikka.shizuku:api:13.1.0"
    implementation "dev.rikka.shizuku:provider:13.1.0"
    // 为了支持 minSdk 18，必须将 material >= 1.9.0
    implementation 'com.google.android.material:material:1.11.0'

    testImplementation 'junit:junit:4.13.2'
}
